
[window]
padding = {x = 10, y = 10}
startup_mode = "Windowed"
decorations = "full"

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"}
]

[font]
size = 12.0

[font.normal]
family = 'MonaspaceNeon'
style = 'semi-bold'

[font.italic]
family = 'MonaspaceRadon'
style = 'semi-bold'

[general]
import = ["~/.config/alacritty/colourscheme.toml"]
