#!/bin/bash

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H-%M-%S)

CAPTURE_DIR=~/Pictures/Catcam/$DATE
CAPTURE_PATH=$CAPTURE_DIR/$TIME.jpg

DROPBOX_PATH=/cat-camera/$DATE/$TIME.jpg

mkdir -p $CAPTURE_DIR
libcamera-jpeg -n --autofocus-on-capture=1 --hflip=1 --vflip=1 --immediate -o $CAPTURE_PATH
~/Repos/Dropbox-Uploader/dropbox_uploader.sh upload $CAPTURE_PATH $DROPBOX_PATH

